USE [FINPOS_TICARI]
GO

/****** Object:  Table [dbo].[TBL_ODEME_INDIRIM]    Script Date: 27.01.2025 23:53:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_ODEME_INDIRIM](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[ADI] [nvarchar](50) NULL,
	[DURUM] [nvarchar](50) NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBL_ODEME_INDIRIM] ADD  CONSTRAINT [DF_TBL_ODEME_INDIRIM_DURUM]  DEFAULT (N'Aktif') FOR [DURUM]
GO


